### ISSUE TITLE
Update to reflect new minimum requirement for PHP7

### ISSUE THREAD

**Issue by vivace-io** [eveseat/docs#5]
Specifically referencing Ubuntu installation instructions [found here](http://seat-docs.readthedocs.io/en/latest/setup_guides/ubuntu1404/). But basically, docs just need some touchups to reflect the new minimum PHP requirements.

I'm fairly certain 14.04 has PHP7.0 in aptitude, too.

I'll get working on it if no one else has time.

**Comment by warlof** [comment]
hey ya, fill free to send PR ;)

**Comment by leonjza** [comment]
@vivace-io mind opening this issue on the main repo https://github.com/eveseat/seat? Its hard to track issues in separate repos like this ;)

Once its done ill close the issues tracker here.

**Comment by leonjza** [comment]
Spent some time today updating the docs. Also included the new installer tools etc. Going to close this. If there are more issues, feel free to open on the main repo ;)
